"""
conditions.py — Generate _conditions.py files from Veri DSL contracts.

For each ValDecl, ImportedDecl, or ExternDecl with contracts, produces:
  - fn__requires(*args) -> bool  (from REQUIRES)
  - fn__ensures(result, *args) -> bool  (from ENSURES)

The generated file is imported by the main .py wrapper module.
"""

from typing import List, Optional

from veri_ast import (
    VeriDslProgram, Declaration,
    ModuleDecl, OpenDecl, 
    TypeAbstract, TypeAlias, TypeRecord, TypeVariant,
    LetDecl, ValDecl, ImportedDecl, ExternDecl, PragmaDecl,
    Binder, PrePost,
    Expr, Var, QualifiedVar, Const, App, BinOp, UnaryOp,
    FieldAccess, RecordUpdate, IfExpr, Match,
    Forall, Exists, Lambda,
    ArrayIndex, ArrayLen, Len,
    Contains, Sel, Live, Modifies,
    BufferGet, BufferLength,
    Pattern, PatWild, PatVar, PatConst, PatCons, PatApp,
)


class ConditionsPrinter:
    """Emit VeriDslProgram contracts as Python condition functions."""

    def __init__(self):
        self.lines: List[str] = []
        self._imported_functions: List[str] = []

    def emit(self, program: VeriDslProgram, module_name: str = "generated") -> str:
        """Generate _conditions.py source text."""
        self.lines = []
        self._imported_functions = []

        self._line(f'"""Runtime contract conditions for {module_name}.veri.md.')
        self._line(f'Generated by Veri DSL Python-assert backend.')
        self._line(f'"""')
        self._line()

        # Emit imports for types and other functions referenced in conditions
        # Collect symbols referenced in contracts
        symbols = self._collect_referenced_symbols(program)
        if symbols:
            self._line(f"from {module_name} import (")
            self._indent()
            for sym in sorted(symbols):
                self._line(f"{sym},")
            self._dedent()
            self._line(f")")
        self._line()

        # Build refinement map for type-level assertions
        ref_map = self._build_refinement_map(program)

        # Track cross-module imports so we generate proper import-from statements
        cross_imports: dict = {}  # module_path → set of function names

        for decl in program.decls:
            if isinstance(decl, (ValDecl, ImportedDecl, ExternDecl)):
                self._emit_conditions(decl, ref_map=ref_map)
            # Collect cross-module function imports for re-export
            if isinstance(decl, ImportedDecl) and decl.module_path:
                if decl.module_path not in cross_imports:
                    cross_imports[decl.module_path] = set()
                cross_imports[decl.module_path].add(decl.name)

        # Emit re-exports from cross-module condition imports
        if cross_imports:
            self._line()
            self._line(f"# Conditions imported from other Veri DSL specs")
            for mod_path, fns in sorted(cross_imports.items()):
                mod_name = mod_path.split('.')[-1].lower()
                for fn in sorted(fns):
                    # Re-export: from other_spec_conditions import fn__requires, fn__ensures
                    self._line(f"from {mod_name}_conditions import {fn}__requires, {fn}__ensures")

        return '\n'.join(self.lines)

    def _indent(self):
        # Track indent level via the last line check in _line
        self._indent_level = getattr(self, '_indent_level', 0) + 1

    def _dedent(self):
        self._indent_level = max(0, getattr(self, '_indent_level', 1) - 1)

    def _line(self, text: str = ''):
        level = getattr(self, '_indent_level', 0)
        if text:
            self.lines.append('    ' * level + text)
        else:
            self.lines.append('')

    def _collect_referenced_symbols(self, program: VeriDslProgram) -> set:
        """Collect all type/variable names referenced in contracts."""
        symbols = set()
        for decl in program.decls:
            if isinstance(decl, (ValDecl, ImportedDecl, ExternDecl)):
                contract = decl.contract
                if contract.requires:
                    self._collect_from_expr(contract.requires, symbols)
                if contract.ensures:
                    self._collect_from_expr(contract.ensures, symbols)
        return symbols

    def _build_refinement_map(self, program: VeriDslProgram) -> dict:
        """Build {type_name: (binder_name, predicate_expr)} for refined types."""
        from veri_ast import RefinedType
        ref_map = {}
        for decl in program.decls:
            if isinstance(decl, TypeAlias) and isinstance(decl.typ, RefinedType):
                rt = decl.typ
                # Collect Var names used in the predicate so we can substitute
                var_names = []
                self._collect_ref_vars(rt.predicate, var_names)
                ref_map[decl.name] = {
                    "binder_name": rt.binder.name,
                    "predicate": rt.predicate,
                    "var_names": var_names,
                }
        return ref_map

    def _collect_ref_vars(self, expr: Expr, vars_list: list):
        """Collect Var names from an expression (for substitution)."""
        if isinstance(expr, Var):
            if expr.name not in vars_list:
                vars_list.append(expr.name)
        elif isinstance(expr, QualifiedVar):
            pass
        elif isinstance(expr, App):
            # Collect from argument positions, NOT function position
            for a in expr.args:
                self._collect_ref_vars(a, vars_list)
        elif isinstance(expr, BinOp):
            self._collect_ref_vars(expr.left, vars_list)
            self._collect_ref_vars(expr.right, vars_list)
        elif isinstance(expr, UnaryOp):
            self._collect_ref_vars(expr.expr, vars_list)
        elif isinstance(expr, FieldAccess):
            self._collect_ref_vars(expr.expr, vars_list)
        elif isinstance(expr, IfExpr):
            self._collect_ref_vars(expr.cond, vars_list)
            self._collect_ref_vars(expr.then_expr, vars_list)
            self._collect_ref_vars(expr.else_expr, vars_list)
        elif isinstance(expr, Match):
            self._collect_ref_vars(expr.expr, vars_list)
            for c in expr.cases:
                self._collect_ref_vars(c.expr, vars_list)
        elif isinstance(expr, (Forall, Exists)):
            self._collect_ref_vars(expr.body, vars_list)
        elif isinstance(expr, Lambda):
            self._collect_ref_vars(expr.body, vars_list)

    def _collect_from_expr(self, expr: Expr, symbols: set):
        """Walk an expression and collect referenced names."""
        if isinstance(expr, Var):
            if expr.name[0].isupper() and expr.name not in ('True', 'False', 'None', 'Some'):
                symbols.add(expr.name)
        elif isinstance(expr, QualifiedVar):
            parts = expr.path.parts
            for p in parts:
                if p[0].isupper():
                    symbols.add(p)
        elif isinstance(expr, App):
            self._collect_from_expr(expr.func, symbols)
            for a in expr.args:
                self._collect_from_expr(a, symbols)
        elif isinstance(expr, BinOp):
            self._collect_from_expr(expr.left, symbols)
            self._collect_from_expr(expr.right, symbols)
        elif isinstance(expr, UnaryOp):
            self._collect_from_expr(expr.expr, symbols)
        elif isinstance(expr, FieldAccess):
            self._collect_from_expr(expr.expr, symbols)
        elif isinstance(expr, IfExpr):
            self._collect_from_expr(expr.cond, symbols)
            self._collect_from_expr(expr.then_expr, symbols)
            self._collect_from_expr(expr.else_expr, symbols)
        elif isinstance(expr, Match):
            self._collect_from_expr(expr.expr, symbols)
            for c in expr.cases:
                self._collect_from_expr(c.expr, symbols)
        elif isinstance(expr, (Forall, Exists)):
            self._collect_from_expr(expr.body, symbols)
        elif isinstance(expr, Lambda):
            self._collect_from_expr(expr.body, symbols)

    def _emit_conditions(self, decl, ref_map=None):
        """Emit requires/ensures functions for a single declaration.

        Includes implicit type assertions from refined types (WHERE predicates)
        on parameters and return values.

        For ImportedDecl with a module_path, conditions come from the other
        spec's _conditions.py — we skip local generation and emit a re-export
        in _build_refinement_map instead.
        """
        # Cross-module imports: conditions come from the other spec
        if isinstance(decl, ImportedDecl) and decl.module_path:
            return

        fn_name = decl.name
        params = decl.params
        contract = decl.contract

        param_names = [p.name for p in params]
        ref_map = ref_map or {}

        # ── REQUIRES ──
        req_params = ', '.join(param_names)
        self._line(f"def {fn_name}__requires({req_params}):")

        # Build requires clauses: explicit + implicit type assertions for params
        req_clauses = []

        # Explicit requires from Veri DSL spec
        if contract.requires:
            req_clauses.append(self._expr(contract.requires))

        # Implicit type assertions from refined type params
        for param in params:
            type_name = self._resolve_type_name(param.typ)
            if type_name and type_name in ref_map:
                ref_info = ref_map[type_name]
                # Substitute refinement variable name with actual param name
                pred_text = self._expr_with_rename(
                    ref_info["predicate"],
                    ref_info["var_names"],
                    param.name,
                )
                req_clauses.append(pred_text)

        if req_clauses:
            body = ' and '.join(f"({c})" for c in req_clauses)
            self._line(f"    return {body}")
        else:
            self._line(f"    return True")
        self._line()

        # ── ENSURES ──
        ens_params = ', '.join(['result'] + param_names)
        self._line(f"def {fn_name}__ensures({ens_params}):")

        ens_clauses = []

        # Explicit ensures from Veri DSL spec
        if contract.ensures:
            ens_clauses.append(self._expr(contract.ensures))

        # Implicit type assertion from return type refinement
        return_type_name = self._resolve_type_name(decl.return_type)
        if return_type_name and return_type_name in ref_map:
            ref_info = ref_map[return_type_name]
            pred_text = self._expr_with_rename(
                ref_info["predicate"],
                ref_info["var_names"],
                "result",
            )
            ens_clauses.append(pred_text)

        if ens_clauses:
            body = ' and '.join(f"({c})" for c in ens_clauses)
            self._line(f"    return {body}")
        else:
            self._line(f"    return True")
        self._line()

    def _resolve_type_name(self, typ) -> Optional[str]:
        """Extract the type name from a type annotation, if it's a named type."""
        if typ is None:
            return None
        from veri_ast import NamedType, PrimType
        if isinstance(typ, NamedType):
            return typ.path.parts[-1] if typ.path.parts else None
        if isinstance(typ, PrimType):
            return typ.name
        if hasattr(typ, 'name'):
            return typ.name
        return None

    def _expr_with_rename(self, expr: Expr, old_names: list, new_name: str) -> str:
        """Translate expression, renaming old_names to new_name in Var nodes."""
        if isinstance(expr, Var):
            if expr.name in old_names:
                return new_name
            return expr.name
        elif isinstance(expr, QualifiedVar):
            return str(expr.path)
        elif isinstance(expr, Const):
            if expr.value is None: return 'None'
            return str(expr.value).lower() if isinstance(expr.value, bool) else repr(expr.value)
        elif isinstance(expr, App):
            func = self._expr_with_rename(expr.func, old_names, new_name)
            if isinstance(expr.func, Var) and expr.func.name == 'Cons' and len(expr.args) == 2:
                h = self._expr_with_rename(expr.args[0], old_names, new_name)
                t = self._expr_with_rename(expr.args[1], old_names, new_name)
                if t == '[]': return f'[{h}]'
                return f'[{h}] + {t}'
            if isinstance(expr.func, Var) and expr.func.name == 'Some' and len(expr.args) == 1:
                return self._expr_with_rename(expr.args[0], old_names, new_name)
            args = ', '.join(self._expr_with_rename(a, old_names, new_name) for a in expr.args)
            return f"{func}({args})"
        elif isinstance(expr, BinOp):
            left = self._expr_with_rename(expr.left, old_names, new_name)
            right = self._expr_with_rename(expr.right, old_names, new_name)
            op = expr.op
            if op == 'GT': op = '>'
            elif op == 'LT': op = '<'
            elif op == 'LE': op = '<='
            elif op == 'GE': op = '>='
            if op in ('and', '/\\'): op_str = 'and'
            elif op in ('or', '\\/'): op_str = 'or'
            elif op in ('=', '==', '=='): op_str = '=='
            elif op == '!=': op_str = '!='
            elif op == '==>': return f"(not ({left}) or ({right}))"
            else: op_str = op
            return f"({left} {op_str} {right})"
        elif isinstance(expr, UnaryOp):
            inner = self._expr_with_rename(expr.expr, old_names, new_name)
            return f"(not {inner})" if expr.op in ('not', '~') else f"({expr.op}{inner})"
        elif isinstance(expr, FieldAccess):
            obj = self._expr_with_rename(expr.expr, old_names, new_name)
            return f"{obj}.{expr.field}"
        elif isinstance(expr, Len):
            return f"len({self._expr_with_rename(expr.expr, old_names, new_name)})"
        elif isinstance(expr, IfExpr):
            cond = self._expr_with_rename(expr.cond, old_names, new_name)
            then_expr = self._expr_with_rename(expr.then_expr, old_names, new_name)
            else_expr = self._expr_with_rename(expr.else_expr, old_names, new_name)
            return f"({then_expr} if {cond} else {else_expr})"
        else:
            return self._expr(expr)

    # ── Expression → Python string ───────────────────────────────────────

    def _expr(self, expr: Expr) -> str:
        """Translate an Veri DSL expression to a Python expression string."""
        if isinstance(expr, Const):
            if expr.value is None:
                return 'None'
            if isinstance(expr.value, bool):
                return 'True' if expr.value else 'False'
            if isinstance(expr.value, str):
                return repr(expr.value)
            return str(expr.value)

        elif isinstance(expr, Var):
            if expr.name == 'Nil':
                return '[]'
            return expr.name

        elif isinstance(expr, QualifiedVar):
            return str(expr.path)

        elif isinstance(expr, App):
            func = self._expr(expr.func)
            # Cons(h, t) → list syntax
            if isinstance(expr.func, Var) and expr.func.name == 'Cons' and len(expr.args) == 2:
                h = self._expr(expr.args[0])
                t = self._expr(expr.args[1])
                if t == '[]':
                    return f'[{h}]'
                return f'[{h}] + {t}'
            # Some -> x (unwrap from optional)
            if isinstance(expr.func, Var) and expr.func.name == 'Some' and len(expr.args) == 1:
                return self._expr(expr.args[0])
            args = ', '.join(self._expr(a) for a in expr.args)
            return f"{func}({args})"

        elif isinstance(expr, BinOp):
            left = self._expr(expr.left)
            right = self._expr(expr.right)
            op = expr.op
            # Normalize Veri DSL operator tokens
            if op == 'GT': op = '>'
            elif op == 'LT': op = '<'
            elif op == 'LE': op = '<='
            elif op == 'GE': op = '>='

            # Veri DSL operators → Python
            if op in ('and', '/\\'):
                op_str = 'and'
            elif op in ('or', '\\/'):
                op_str = 'or'
            elif op == 'not':
                op_str = 'not'
            elif op == '==>':
                # a ==> b  →  (not a) or b
                return f"(not ({left}) or ({right}))"
            elif op in ('=', '==', '=='):
                op_str = '=='
            elif op == '!=':
                op_str = '!='
            else:
                op_str = op  # +, -, *, /, %, <, >, <=, >=

            # Parenthesize simple binop combos for safety
            return f"({left} {op_str} {right})"

        elif isinstance(expr, UnaryOp):
            inner = self._expr(expr.expr)
            if expr.op == 'not' or expr.op == '~':
                return f"(not {inner})"
            elif expr.op == '-':
                return f"(-{inner})"
            return f"({expr.op}{inner})"

        elif isinstance(expr, FieldAccess):
            obj = self._expr(expr.expr)
            return f"{obj}.{expr.field}"

        elif isinstance(expr, RecordUpdate):
            obj = self._expr(expr.expr)
            updates = ', '.join(f"{f}={self._expr(v)}" for f, v in expr.updates)
            return f"{{**{obj}, {updates}}}"

        elif isinstance(expr, IfExpr):
            cond = self._expr(expr.cond)
            then_expr = self._expr(expr.then_expr)
            else_expr = self._expr(expr.else_expr)
            return f"({then_expr} if {cond} else {else_expr})"

        elif isinstance(expr, Len):
            return f"len({self._expr(expr.expr)})"

        elif isinstance(expr, Forall):
            body = self._expr(expr.body)
            # FORALL x IN xs: body  →  all(body for x in xs)
            if expr.binders:
                b = expr.binders[0]
                iter_name = b.name
                # Extract the "IN" range
                if isinstance(b.typ, Var):
                    range_expr = b.typ.name
                else:
                    range_expr = self._type(b.typ)
                loop_var = iter_name
                return f"all({body} for {loop_var} in {range_expr})"
            return f"all({body})"

        elif isinstance(expr, Exists):
            body = self._expr(expr.body)
            if expr.binders:
                b = expr.binders[0]
                iter_name = b.name
                if isinstance(b.typ, Var):
                    range_expr = b.typ.name
                else:
                    range_expr = self._type(b.typ)
                loop_var = iter_name
                return f"any({body} for {loop_var} in {range_expr})"
            return f"any({body})"

        elif isinstance(expr, Lambda):
            params = ', '.join(expr.params)
            body = self._expr(expr.body)
            return f"(lambda {params}: {body})"

        elif isinstance(expr, Match):
            # Match → if/elif chain (Python match is Python 3.10+)
            matched = self._expr(expr.expr)
            return self._match_to_if(matched, expr)

        elif isinstance(expr, ArrayIndex):
            arr = self._expr(expr.arr)
            idx = self._expr(expr.index)
            return f"{arr}[{idx}]"

        else:
            return f"<{type(expr).__name__}>"

    def _type(self, typ) -> str:
        """Translate an Veri DSL type to Python annotation string."""
        from veri_ast import PrimType, TypeVar, NamedType, AppType, ListType, OptionType, TupleType
        if hasattr(typ, 'name'):
            name = typ.name
            if name in ('int', 'nat', 'int32', 'int64', 'uint32', 'uint64', 'byte'):
                return 'int'
            if name == 'bool':
                return 'bool'
            if name == 'string':
                return 'str'
            if name == 'float64' or name == 'float32':
                return 'float'
            return name
        if isinstance(typ, ListType):
            return f'list[{self._type(typ.elem)}]'
        if isinstance(typ, OptionType):
            return f'{self._type(typ.elem)} | None'
        if isinstance(typ, TupleType):
            return '(' + ', '.join(self._type(t) for t in typ.items) + ')'
        if isinstance(typ, NamedType):
            return '.'.join(typ.path.parts)
        if isinstance(typ, AppType):
            return self._type(typ.func)
        return str(typ)

    def _match_to_if(self, matched: str, expr: Match) -> str:
        """Convert match expression to nested if/elif/else."""
        if not expr.cases:
            return "None"

        # Build nested ternary: A if cond else B if cond else C
        def _case_to_ternary(cases, idx=0):
            if idx >= len(cases):
                return "None"
            case = cases[idx]
            pattern = case.pattern
            body = self._expr(case.expr)

            if isinstance(pattern, PatWild):
                return body
            elif isinstance(pattern, PatVar):
                return body  # binds variable, but for conditions we emit body
            elif isinstance(pattern, PatConst):
                val = pattern.value
                if val is None:
                    return f"({body} if {matched} is None else {_case_to_ternary(cases, idx + 1)})"
                return f"({body} if {matched} == {val} else {_case_to_ternary(cases, idx + 1)})"
            elif isinstance(pattern, PatApp):
                name = pattern.name
                if name == 'None':
                    return f"({body} if {matched} is None else {_case_to_ternary(cases, idx + 1)})"
                if name == 'Some' and pattern.args:
                    inner = pattern.args[0]
                    if isinstance(inner, PatVar):
                        return f"({body} if {matched} is not None else {_case_to_ternary(cases, idx + 1)})"
                return f"({body} if isinstance({matched}, {name}) else {_case_to_ternary(cases, idx + 1)})"
            elif isinstance(pattern, PatCons):
                # [hd, *tl] → check list + destructure
                return f"({body} if isinstance({matched}, list) and len({matched}) > 0 else {_case_to_ternary(cases, idx + 1)})"
            else:
                return f"({body} else {_case_to_ternary(cases, idx + 1)})"

        return _case_to_ternary(expr.cases)
