"""
printer.py — Generate _conditions.py from Veri DSL contracts.

Decorators go on the *real implementation code*, not on generated wrappers.

This module now only generates the _conditions.py file (pre/post functions).
The @contract decorator from python_runtime is applied by the library author:
  from python_runtime import contract
  from my_spec_conditions import add_element__requires, add_element__ensures

  @contract(requires=add_element__requires, ensures=add_element__ensures)
  def add_element(existing, new_elem):
      ...

To verify real code has correct decorators, use the verify CLI:
  python -m backend.python.verify my_spec.veri.md my_implementation.py
"""

from typing import List, Optional

from veri_ast import (
    VeriDslProgram, Declaration,
    ModuleDecl, OpenDecl,
    TypeAbstract, TypeAlias, TypeRecord, TypeVariant,
    LetDecl, ValDecl, ImportedDecl, ExternDecl, PragmaDecl,
    Binder, PrePost,
    Expr, Var, QualifiedVar, Const, App, BinOp, UnaryOp,
    FieldAccess, RecordUpdate, IfExpr, Match,
    Forall, Exists, Lambda,
    ArrayIndex, ArrayLen, Len,
    Contains, Sel, Live, Modifies,
    BufferGet, BufferLength,
    Pattern, PatWild, PatVar, PatConst, PatCons, PatApp,
)


class ConditionsPrinter:
    """Emit VeriDslProgram contracts as Python condition functions."""

    def __init__(self):
        self.lines: List[str] = []
        self._imported_functions: List[str] = []

    def emit(self, program: VeriDslProgram, module_name: str = "generated") -> str:
        """Generate _conditions.py source text."""
        self.lines = []
        self._imported_functions = []

        self._line(f'"""Runtime contract conditions for {module_name}.veri.md.')
        self._line(f'Generated by Veri DSL Python-assert backend.')
        self._line(f'"""')
        self._line()

        # Emit imports for types and other functions referenced in conditions
        symbols = self._collect_referenced_symbols(program)
        if symbols:
            self._line(f"from {module_name} import (")
            self._indent()
            for sym in sorted(symbols):
                self._line(f"{sym},")
            self._dedent()
            self._line(f")")
        self._line()

        for decl in program.decls:
            if isinstance(decl, (ValDecl, ImportedDecl, ExternDecl)):
                self._emit_conditions(decl)

        return '\n'.join(self.lines)

    def _indent(self):
        self._indent_level = getattr(self, '_indent_level', 0) + 1

    def _dedent(self):
        self._indent_level = max(0, getattr(self, '_indent_level', 1) - 1)

    def _line(self, text: str = ''):
        level = getattr(self, '_indent_level', 0)
        if text:
            self.lines.append('    ' * level + text)
        else:
            self.lines.append('')

    def _collect_referenced_symbols(self, program: VeriDslProgram) -> set:
        """Collect all type/variable names referenced in contracts."""
        symbols = set()
        for decl in program.decls:
            if isinstance(decl, (ValDecl, ImportedDecl, ExternDecl)):
                contract = decl.contract
                if contract.requires:
                    self._collect_from_expr(contract.requires, symbols)
                if contract.ensures:
                    self._collect_from_expr(contract.ensures, symbols)
        return symbols

    def _collect_from_expr(self, expr: Expr, symbols: set):
        if isinstance(expr, Var):
            if expr.name[0].isupper() and expr.name not in ('True', 'False', 'None', 'Some'):
                symbols.add(expr.name)
        elif isinstance(expr, QualifiedVar):
            parts = expr.path.parts
            for p in parts:
                if p[0].isupper():
                    symbols.add(p)
        elif isinstance(expr, App):
            self._collect_from_expr(expr.func, symbols)
            for a in expr.args:
                self._collect_from_expr(a, symbols)
        elif isinstance(expr, BinOp):
            self._collect_from_expr(expr.left, symbols)
            self._collect_from_expr(expr.right, symbols)
        elif isinstance(expr, UnaryOp):
            self._collect_from_expr(expr.expr, symbols)
        elif isinstance(expr, FieldAccess):
            self._collect_from_expr(expr.expr, symbols)
        elif isinstance(expr, IfExpr):
            self._collect_from_expr(expr.cond, symbols)
            self._collect_from_expr(expr.then_expr, symbols)
            self._collect_from_expr(expr.else_expr, symbols)
        elif isinstance(expr, Match):
            self._collect_from_expr(expr.expr, symbols)
            for c in expr.cases:
                self._collect_from_expr(c.expr, symbols)
        elif isinstance(expr, (Forall, Exists)):
            self._collect_from_expr(expr.body, symbols)
        elif isinstance(expr, Lambda):
            self._collect_from_expr(expr.body, symbols)

    def _emit_conditions(self, decl):
        fn_name = decl.name
        params = decl.params
        contract = decl.contract
        param_names = [p.name for p in params]

        # REQUIRES
        if contract.requires:
            req_params = ', '.join(param_names)
            self._line(f"def {fn_name}__requires({req_params}):")
            body = self._expr(contract.requires)
            self._line(f"    return {body}")
            self._line()
        else:
            req_params = ', '.join(param_names)
            self._line(f"def {fn_name}__requires({req_params}):")
            self._line(f"    return True")
            self._line()

        # ENSURES
        if contract.ensures:
            ens_params = ', '.join(['result'] + param_names)
            self._line(f"def {fn_name}__ensures({ens_params}):")
            body = self._expr(contract.ensures)
            self._line(f"    return {body}")
            self._line()
        else:
            ens_params = ', '.join(['result'] + param_names)
            self._line(f"def {fn_name}__ensures({ens_params}):")
            self._line(f"    return True")
            self._line()

    # ── Expression → Python string ───────────────────────────────────────

    def _expr(self, expr: Expr) -> str:
        if isinstance(expr, Const):
            if expr.value is None:
                return 'None'
            if isinstance(expr.value, bool):
                return 'True' if expr.value else 'False'
            if isinstance(expr.value, str):
                return repr(expr.value)
            return str(expr.value)

        elif isinstance(expr, Var):
            if expr.name == 'Nil':
                return '[]'
            return expr.name

        elif isinstance(expr, QualifiedVar):
            return str(expr.path)

        elif isinstance(expr, App):
            func = self._expr(expr.func)
            if isinstance(expr.func, Var) and expr.func.name == 'Cons' and len(expr.args) == 2:
                h = self._expr(expr.args[0])
                t = self._expr(expr.args[1])
                if t == '[]':
                    return f'[{h}]'
                return f'[{h}] + {t}'
            if isinstance(expr.func, Var) and expr.func.name == 'Some' and len(expr.args) == 1:
                return self._expr(expr.args[0])
            args = ', '.join(self._expr(a) for a in expr.args)
            return f"{func}({args})"

        elif isinstance(expr, BinOp):
            left = self._expr(expr.left)
            right = self._expr(expr.right)
            op = expr.op
            if op == 'GT': op = '>'
            elif op == 'LT': op = '<'
            elif op == 'LE': op = '<='
            elif op == 'GE': op = '>='

            if op in ('and', '/\\'):
                op_str = 'and'
            elif op in ('or', '\\/'):
                op_str = 'or'
            elif op == 'not':
                op_str = 'not'
            elif op == '==>':
                return f"(not ({left}) or ({right}))"
            elif op in ('=', '==', '=='):
                op_str = '=='
            elif op == '!=':
                op_str = '!='
            else:
                op_str = op

            return f"({left} {op_str} {right})"

        elif isinstance(expr, UnaryOp):
            inner = self._expr(expr.expr)
            if expr.op == 'not' or expr.op == '~':
                return f"(not {inner})"
            elif expr.op == '-':
                return f"(-{inner})"
            return f"({expr.op}{inner})"

        elif isinstance(expr, FieldAccess):
            obj = self._expr(expr.expr)
            return f"{obj}.{expr.field}"

        elif isinstance(expr, RecordUpdate):
            obj = self._expr(expr.expr)
            updates = ', '.join(f"{f}={self._expr(v)}" for f, v in expr.updates)
            return f"{{**{obj}, {updates}}}"

        elif isinstance(expr, IfExpr):
            cond = self._expr(expr.cond)
            then_expr = self._expr(expr.then_expr)
            else_expr = self._expr(expr.else_expr)
            return f"({then_expr} if {cond} else {else_expr})"

        elif isinstance(expr, Len):
            return f"len({self._expr(expr.expr)})"

        elif isinstance(expr, Forall):
            body = self._expr(expr.body)
            if expr.binders:
                b = expr.binders[0]
                iter_name = b.name
                if isinstance(b.typ, Var):
                    range_expr = b.typ.name
                else:
                    range_expr = self._type(b.typ)
                loop_var = iter_name
                return f"all({body} for {loop_var} in {range_expr})"
            return f"all({body})"

        elif isinstance(expr, Exists):
            body = self._expr(expr.body)
            if expr.binders:
                b = expr.binders[0]
                iter_name = b.name
                if isinstance(b.typ, Var):
                    range_expr = b.typ.name
                else:
                    range_expr = self._type(b.typ)
                loop_var = iter_name
                return f"any({body} for {loop_var} in {range_expr})"
            return f"any({body})"

        elif isinstance(expr, Lambda):
            params = ', '.join(expr.params)
            body = self._expr(expr.body)
            return f"(lambda {params}: {body})"

        elif isinstance(expr, Match):
            matched = self._expr(expr.expr)
            return self._match_to_if(matched, expr)

        elif isinstance(expr, ArrayIndex):
            arr = self._expr(expr.arr)
            idx = self._expr(expr.index)
            return f"{arr}[{idx}]"

        else:
            return f"<{type(expr).__name__}>"

    def _type(self, typ) -> str:
        from veri_ast import PrimType, TypeVar, NamedType, AppType, ListType, OptionType, TupleType
        if hasattr(typ, 'name'):
            name = typ.name
            if name in ('int', 'nat', 'int32', 'int64', 'uint32', 'uint64', 'byte'):
                return 'int'
            if name == 'bool':
                return 'bool'
            if name == 'string':
                return 'str'
            if name == 'float64' or name == 'float32':
                return 'float'
            return name
        if isinstance(typ, ListType):
            return f'list[{self._type(typ.elem)}]'
        if isinstance(typ, OptionType):
            return f'{self._type(typ.elem)} | None'
        if isinstance(typ, TupleType):
            return '(' + ', '.join(self._type(t) for t in typ.items) + ')'
        if isinstance(typ, NamedType):
            return '.'.join(typ.path.parts)
        if isinstance(typ, AppType):
            return self._type(typ.func)
        return str(typ)

    def _match_to_if(self, matched: str, expr: Match) -> str:
        if not expr.cases:
            return "None"

        def _case_to_ternary(cases, idx=0):
            if idx >= len(cases):
                return "None"
            case = cases[idx]
            pattern = case.pattern
            body = self._expr(case.expr)

            if isinstance(pattern, PatWild):
                return body
            elif isinstance(pattern, PatVar):
                return body
            elif isinstance(pattern, PatConst):
                val = pattern.value
                if val is None:
                    return f"({body} if {matched} is None else {_case_to_ternary(cases, idx + 1)})"
                return f"({body} if {matched} == {val} else {_case_to_ternary(cases, idx + 1)})"
            elif isinstance(pattern, PatApp):
                name = pattern.name
                if name == 'None':
                    return f"({body} if {matched} is None else {_case_to_ternary(cases, idx + 1)})"
                if name == 'Some' and pattern.args:
                    inner = pattern.args[0]
                    if isinstance(inner, PatVar):
                        return f"({body} if {matched} is not None else {_case_to_ternary(cases, idx + 1)})"
                return f"({body} if isinstance({matched}, {name}) else {_case_to_ternary(cases, idx + 1)})"
            elif isinstance(pattern, PatCons):
                return f"({body} if isinstance({matched}, list) and len({matched}) > 0 else {_case_to_ternary(cases, idx + 1)})"
            else:
                return f"({body} else {_case_to_ternary(cases, idx + 1)})"

        return _case_to_ternary(expr.cases)
